import { NextPage } from "next";
import Head from "next/head";
import Dashboard from "~/components/dashboard/dashboard";

const index: NextPage = () => {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-helvetica bg-[#F4F4F0]">
        <Dashboard />
      </main>
    </>
  );
};

export default index;
